name: Deploy to GH Pages

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Build site
        run: lektor build

      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
          ssh-add ~/.ssh/github_actions

      - name: Deploy site
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: lektor deploy ghpages
